### PR TITLE
restructured folders for flask app

### PR DESCRIPTION
**Pull request by koolgax99**
I have created the basic files needed for the flask app which includes
templates Folder (includes all the html files)
static folder (includes all the css, js and libs used by the html files)
app.py
requirements.txt
config.py

### CODE REVIEW

**Comment by Dharmesh-Poddar** [comment]
@koolgax99  send the link of your version of the project after deploying somewhere.

**Comment by koolgax99** [comment]
https://precision-farming-demo.herokuapp.com/

@Dharmesh-Poddar here is the link to the flask app deployed on heroku

**Comment by Dharmesh-Poddar** [comment]
@koolgax99  the background image of the main page is missing in your version and please also resolve the merge conflicts .

**Comment by koolgax99** [comment]
@Dharmesh-Poddar can you please check now and merge my pull request into your repo. 

The link to the website is [https://precision-farming-demo.herokuapp.com/](url)

also there are no merge conflicts now

**Pull request merged**
